### PR TITLE
Fixed Integration Bugs

### PR DESCRIPTION
**Pull request by ruthvikm**

### CODE REVIEW

**Review by SwindleA — APPROVED** [review]
Looks good. Builds and the git ignore works correctly.

**Review by joefol — COMMENTED** [review]
It looks good and builds fine. However, I am getting errors in the adoc section for image file paths. It loads on my local machine and seems to work. Are you getting errors on your machine? Look at lines 30 and 32 in gettingStarted.adoc.

**Comment by ruthvikm** [comment]
> It looks good and builds fine. However, I am getting errors in the adoc section for image file paths. It loads on my local machine and seems to work. Are you getting errors on your machine? Look at lines 30 and 32 in gettingStarted.adoc.

Yes, locally the image path is different. We need to consider the path from where these adocs pull images on gh-pages branch. To test that, build asciidoc using "./gradlew asciidoctor", check if the images are showing up by opening index.html which will be available in the build/docs/asciidoc directory

**Comment by SwindleA** [comment]
> It looks good and builds fine. However, I am getting errors in the adoc section for image file paths. It loads on my local machine and seems to work. Are you getting errors on your machine? Look at lines 30 and 32 in gettingStarted.adoc.

I see the error too but it seems to build fine because the current documentation has the images showing up.

**Review by joefol — APPROVED** [review]
Looks good!

**Pull request merged**
