### PR TITLE
Began implementation of the active/passive buzzer files

### PR DESCRIPTION
**Pull request by adelgadoj3**
Created the appropriate functions needed for the buzzer helper class:

- Initialize
- turnOn
- turnOff
- setFrequency(int Frequency)

Also added the appropriate tags and comments for the file.

### CODE REVIEW

**Review by ruthvikm — COMMENTED** [review]
Make sure to add methods for Active and Passive buzzers in this helper. You can make use of these turnOn() and turnOff() to enable and disable. setFrequency() can be used for both buzzers

**Review by ruthvikm — COMMENTED** [review]
Did you test this on pi?

**Comment by adelgadoj3** [comment]
Not yet, I planned on doing it today, but I left my pi and breadboard at home. I’ll check to see if there is another in the lab and build another breadboard if one’s available. I’ll be there from 10-1 if you have time and want to join.
________________________________
From: Ruthvik Mannem ***@***.***>
Sent: Thursday, February 22, 2024 11:00 PM
To: oss-slu/Pi4Micronaut ***@***.***>
Cc: Alexander Delgado ***@***.***>; Assign ***@***.***>
Subject: [External] Re: [oss-slu/Pi4Micronaut] Began implementation of the active/passive buzzer files (PR #154)

CAUTION: This email is from an external source. Do not click links or open attachments unless you recognize the sender and know the content is safe. When in doubt, please report the email to SLUAware by clicking on the three dots within your email and choosing Report To SLUAware.

@ruthvikm commented on this pull request.

Did you test this on pi?

**Comment by ruthvikm** [comment]
Closing this pull request as the changes are made through another pull request

**Pull request closed without merging**
