### PR TITLE
Speed Sensor Support.

### LINKED ISSUE #244: Speed Sensor Support
Given a Speed Sensor
when an object passes the sensor
then real time data about the speed is provided.

This component will enable the Pi4Micronaut project to measure and monitor the speed of various objects, providing real-time data for control and automation tasks.

**Developer Notes:**
 1. Draw a circuit setup for hardware connections.
 3. Develop functionality to read data from the speed sensor.
      - Create SpeedSensorHelper.java class to handle sensor data.
      - Implement methods to read speed data and convert it to meaningful units (e.g., RPM).
      - Ensure compatibility with various speed sensors by configuring the GPIO pins appropriately.
 5. Create a YAML configuration file for sensor settings.

**Acceptance Criteria:**

- [x]    Functionality to read the speed data from the sensor.
- [x]    Compomnet defined in YAML file. 
    - [ ] name
    - [ ] address
    - [ ] pull_Down
    - [ ] debounce
    - [ ] provider
- [x]    Schematic diagram accurately depicts the wiring.
- [x]    Code comment for each of the functionality is provided.(for developing documentation later)

### PR DESCRIPTION
**Pull request by ThomasMacas**
Fixes #244 

Created Functionality through Helper, Controller files. As well as created documentation for speed sensor by creating an adoc file and a html file. In order to create functionality for a speed sensor, these changed must be made. 

SpeedSensorHelper.java, SpeedSensorController.java, speedSensor.adoc, SpeedSensorHelper.html were created to control the functionality and documentation of a speed sensor. 

Within SpeedSensorHelper.java functions are created in order to handle the requested functionality. to read speed data and convert it to Rotations/Minute(RPMs) the function private void calculateSpeed() is used to convert speed data into RPM. The function public double getRPM() is used to return the RPM calculations. 
The functions: public void initialize(), public void startMeasuring(), public void stopMeasuring() are implemented to handle the operations of the speed sensor. 

Within SpeedSensorController.java functions are created in order to interface with SpeedSensorHelper.java in order to control what the speed sensor does and reports functionality, by return the current operation, and then information error messages if one occurs. 

Within the files speedSensor.adoc, SpeedSensorHelper.html, documentation is created to showcase functionality and specifications in order for a person to implement their Raspberry Pi with a speed sensor using Java

### CODE REVIEW

**Review by leandrumartin — COMMENTED** [review]
Looks good. I don't see anything to fix.

**Review by yrlmanoharreddy — CHANGES_REQUESTED** [review]
The functionality you've implemented for the speed sensor works well and meets the project requirements. However, from a product and code quality perspective, please remove the documentation files since they will be generated automatically. This will help keep the codebase clean and reduce unnecessary clutter. The rest of the implementation, including the YAML configuration and circuit diagrams, looks great—just ensure the auto-generated documentation is handled correctly

**Comment by ThomasMacas** [comment]
> The functionality you've implemented for the speed sensor works well and meets the project requirements. However, from a product and code quality perspective, please remove the documentation files since they will be generated automatically. This will help keep the codebase clean and reduce unnecessary clutter. The rest of the implementation, including the YAML configuration and circuit diagrams, looks great—just ensure the auto-generated documentation is handled correctly

fixed

**Review by yrlmanoharreddy — CHANGES_REQUESTED** [review]
Verify your SpeedSersorHelperTest class and cross verify and make sure all your testcases are passing. 
Please write your yml configuration under particular communication type(under digital-input)

**Review by yrlmanoharreddy — APPROVED** [review]
Added support for a Speed Sensor in the Pi4Micronaut project

**Pull request merged**
