### PR TITLE
Servo Motor Implementation. Issue #8

### PR DESCRIPTION
**Pull request by joefol**
Closes Issue #8

### CODE REVIEW

**Comment by joefol** [comment]
It still needs to be tested on the pi.

**Review by ruthvikm — CHANGES_REQUESTED** [review]
I have tested it and it's not working

**Review by ruthvikm — APPROVED** [review]
I have tested it and works as it should between 0 and 180 degrees

**Review by adelgadoj3 — CHANGES_REQUESTED** [review]
Great comments! It looks great, the only minor thing would be the ex tags for the .adoc file.

**Review by adelgadoj3 — APPROVED** [review]

**Pull request merged**
