### PR TITLE
issue-80 added light sensor compatibility

### PR DESCRIPTION
**Pull request by jyanev**

### CODE REVIEW

**Review by ruthvikm — APPROVED** [review]

**Review by ruthvikm — CHANGES_REQUESTED** [review]
I can't see photoResistorHelper class in full

**Review by ruthvikm — APPROVED** [review]
Looks Good

**Review by ruthvikm — COMMENTED** [review]
I have tested this on my pi. It works

**Review by joefol — APPROVED** [review]
There's a warning for line 55 in the helper, but it builds fine and I see no other problems. Looks good.

**Review by adelgadoj3 — APPROVED** [review]

**Pull request merged**
