### PR TITLE
Tilt Switch implementation. Issue #40

### PR DESCRIPTION
**Pull request by joefol**

### CODE REVIEW

**Review by ruthvikm — COMMENTED** [review]
Looks good. Did you test this on Pi?

**Comment by joefol** [comment]
Tilt switch is working! No issues.

**Review by adelgadoj3 — APPROVED** [review]
Looks great Joe!

(〃￣︶￣)人(￣︶￣〃)

**Review by ruthvikm — APPROVED** [review]
Look good. Please add a few comments in the controller class

**Review by jyanev — APPROVED** [review]
happy

**Review by SwindleA — APPROVED** [review]
image

**Pull request merged**
