### PR TITLE
Removed compiler generated classes

### PR DESCRIPTION
**Pull request by ruthvikm**
Deleted all compiler generated class files from bin folders. Also, added bin to .gitignore

### CODE REVIEW

**Comment by GreihMurray** [comment]
Only potential problem would be if this interferes with any of the GH actions, I can't remember if it will off the top of my head and am currently unable to check

**Comment by kate-holdener** [comment]
Thanks @GreihMurray. Github actions seem happy with this PR. Checks are passing in the PR, and here's a screenshot from the Actions tab
Screen Shot 2023-09-20 at 3 47 39 PM

**Comment by kate-holdener** [comment]
@GreihMurray or @kungfuchicken : This repo requires two approvals for PRs. Can one of you approve?

**Comment by GreihMurray** [comment]
I was more worried about issues with either the docs build or the deployment but I think they both build their own anyway. I'll go ahead and approve, of something breaks down the line bin can just be removed from the gitignore

**Review by GreihMurray — APPROVED** [review]

**Comment by kate-holdener** [comment]
You called it @GreihMurray , I broke the build by merging this:
Screen Shot 2023-09-20 at 4 04 42 PM
Screen Shot 2023-09-20 at 4 04 14 PM

**Comment by GreihMurray** [comment]
That's actually a different issue. Long story short one of the dependencies for deployment has to be in the top level project but we decided not to include bloat code in our deployments. If you just go into the build.gradle in the micronaut pi4j utils folder and comment out everything relating to Nexus publishing (should be the last entry I think) it should work again

**Comment by GreihMurray** [comment]
Or if you give me 20-30 minutes I can fix it

**Comment by kate-holdener** [comment]
@GreihMurray I'll try your suggestion and will share results. Thank you.

**Pull request merged**
