### PR TITLE
Yaml docs

### PR DESCRIPTION
**Pull request by GreihMurray**
Adding examples from the yaml file to the docs along with adding multipin yaml examples and order explanations

### CODE REVIEW

**Review by traison-diedrich — APPROVED** [review]
I am going to approve this but when I generated the index.html using ./gradlew asciidoctor locally and previewed it, I noticed that the regular text was a light grey on top of white which is very hard to read. See attached. Very possible its a previewer error
image

**Comment by GreihMurray** [comment]
> I am going to approve this but when I generated the index.html using ./gradlew asciidoctor locally and previewed it, I noticed that the regular text was a light grey on top of white which is very hard to read. See attached. Very possible its a previewer error image

Yeah thats not supposed to happen. Could you try opening it in a browser? For me the text is black on white

**Comment by traison-diedrich** [comment]
Browser works correctly, sorry for confusion

**Comment by GreihMurray** [comment]
all good man, thanks for checking it

**Review by liusinuo2000 — APPROVED** [review]

**Pull request merged**
